apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pant-api
  namespace: #{NAMESPACE}#
  labels:
    app: pant-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pant-api
    spec:
      containers:
      - name: pant-api
        image: chaos.azurecr.io/pant-api:#{Build.BuildId}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
      imagePullSecrets:
        - name: acr
