apiVersion: v1
kind: Service
metadata:
  name: pant-api
  namespace: #{NAMESPACE}#
  labels:
    app: pant-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: pant-api
